### ISSUE TITLE
Rethink the linking of FB_Object:s

### ISSUE THREAD

**Issue by ahuca** [ahuca/TcBase#13]
At the moment FB_Objects are able to be bound together via its FB_init "constructor". This property has been taken directly from [TcOpen](https://github.com/TcOpenGroup/TcOpen). For their ([TcOpenGroup](https://github.com/TcOpenGroup)) use-case, objects are instantiated within a context, which has "global" shared resources for all the child objects to access. For instance, a [TcoLogger](https://github.com/TcOpenGroup/TcOpen/tree/dev/src/TcoCore/src/XaeTcoCore/TcoCore/POUs/Prototypes/TcoLogger) within a context is available for all child objects to use. Here are a few points to mull over:

1. What are the real benefits of this practice (for our use case)?
2. Does this increases unnecessary and accidental couplings between objects?
3. Should this be the default behaviour for FB_Object? If not, should there be another object like FB_LinkedObject? Hence the final implementation would include FB_Object (resembling current FB_OrphanObject) and FB_LinkedObjects (resembling current FB_Object)

Does @Colho have any thoughts on this?

**Comment by Colho** [comment]
If we are keeping FB_Object as a generic object, that can and will be used as part of data structures, the FB_Object should only contain the basic functionality of a generic object. Functionality for linking objects together should be the responsibility of the higher level data structure, or then another object inherited from FB_Object, as you suggested.

On my opinion inheriting FB_LinkedObject from FB_Object as a separate class is the way to go here, and that can be used if needed. Having the possibility to link generic objects by themselves only enables the user to link something that should not be linked. For example using a list, which consists of FB_Objects, which are then again linked to another FB_Object, totally unrelated to the list. This would result in quite funky data structures.
